before:
    hooks:
        - go mod tidy

builds:
    -
        id: xurls-cli
        main: cmd/xurls/main.go
        binary: xurls

        env:
            - CGO_ENABLED=0

        goos:
            - linux
            - windows
            - darwin
        goarch:
            - amd64
            - 386
            - arm
            - arm64
        ignore:
            - 
                goos: darwin
                goarch: 386
            -
                goos: windows
                goarch: arm
            - 
                goos: windows
                goarch: arm64

        flags:
            - -trimpath

archives:
    -
        id: tgz
        builds: 
            - xurls-cli
        format: tar.gz
        format_overrides:
            -
                goos: windows
                format: zip

checksum:
    algorithm: sha256

announce:
    discord:
        enabled: true
        message_template: '**New Release: {{ .ProjectName }} {{.Tag}}** is published! Check it out at {{ .ReleaseURL }}'